[package]
name = "cookbook-science"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5"
ndarray = { version = "0.15", features = ["approx-0_5"] }
